name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract changelog entry
        id: changelog
        run: |
          set -euo pipefail
          tag="${GITHUB_REF_NAME}"
          version="${tag#v}"

          python3 <<'PY'
import os
import re

tag = os.environ.get("GITHUB_REF_NAME", "")
version = tag[1:] if tag.startswith("v") else tag

with open("CHANGELOG.md", "r", encoding="utf-8") as fh:
    changelog = fh.read()

pattern = re.compile(rf"^## \[{re.escape(version)}\].*?(?=^## \[|\Z)", re.MULTILINE | re.DOTALL)
match = pattern.search(changelog)

entry = match.group(0).strip() if match else f"No changelog entry found for version {version}."

with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as out:
    out.write("body<<'EOF'\n")
    out.write(entry + "\n")
    out.write("EOF\n")
PY

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: false
          body: ${{ steps.changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
